loss_type: 'w2'
testdata_path: test_datasets/CurveFault-A/0.npy 
model_path: Models/CurveFault-A
k: 100
seed: 0
shot_num: 10
rho: 1.8
tau: 0.0001
gamma: 0.45
normalize: True
adap_along: True
sigma: 0.05